name: Deploy to GitHub Pages

# 触发条件：推送到main分支时自动执行
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 设置权限，允许写入内容和页面
permissions:
  contents: read
  pages: write
  id-token: write

# 避免并发部署，取消进行中的部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 构建静态文件
        run: |
          # 创建构建目录
          mkdir -p _site
          
          # 复制所有文件到构建目录
          cp -r * _site/ 2>/dev/null || true
          
          # 移除不需要的文件
          rm -rf _site/.git* _site/_site
          
          # 确保index.html存在
          if [ ! -f "_site/index.html" ]; then
            echo "错误: index.html 文件不存在!"
            exit 1
          fi
          
          echo "构建完成，文件列表:"
          ls -la _site/

      - name: 上传Pages工件
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4